Jenkinsfile (Declarative Pipeline)
pipeline {
    agent { docker { image 'maven:2.8.2' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}